name = "mark_marks/rubine"
version = "0.1.0-rc.0"
description = "An ergonomic, runtime agnostic scheduler for jecs"
authors = ["marked/Mark-Marks"]
repository = "https://git.devmarked.win/marked/rubine"
license = "MIT"
includes = ["lib", "LICENSE", "pesde.toml", "README.md"]

[target]
environment = "luau"
lib = "lib/init.luau"

[indices]
default = "https://github.com/daimond113/pesde-index"

[dependencies]
jecs = { name = "mark_marks/jecs_pesde", version = "^0.4.0" }
jecs_utils = { name = "mark_marks/jecs_utils", version = "^0.1.7-rc.1" }
